version: "3.4"

networks:
  app:

services:
  mongo:
    image: mongo:4.2
    container_name: crm.mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm.app
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
      - 1337:1337
    networks:
      - app
